// Selectable accent themes. The ramps live in accents.css (generated by
// scripts/gen-accents.mjs); this module owns the <html data-accent> attribute
// and its persistence. "sky" is the base skin in styles.css — no attribute.
export type AccentId =
  | "sky"
  | "graphite"
  | "violet"
  | "teal"
  | "rose"
  | "coral"
  | "indigo"
  | "amber"
  | "emerald"
  | "cafe";

// `dot` is each theme's light accent-9 — the swatch shown in pickers.
export const ACCENTS: { id: AccentId; label: string; dot: string }[] = [
  { id: "sky", label: "スカイ", dot: "#24afff" },
  { id: "graphite", label: "グラファイト", dot: "#50606d" },
  { id: "violet", label: "バイオレット", dot: "#7767ef" },
  { id: "teal", label: "ミントティール", dot: "#12bfaa" },
  { id: "rose", label: "ローズ", dot: "#ff6b98" },
  { id: "coral", label: "コーラル", dot: "#fd784b" },
  { id: "indigo", label: "インディゴ", dot: "#5768ef" },
  { id: "amber", label: "アンバーゴールド", dot: "#d39a00" },
  { id: "emerald", label: "エメラルド", dot: "#3ac17d" },
  { id: "cafe", label: "カフェブラウン", dot: "#9c6b3f" },
];

const KEY = "nk-accent";
const listeners = new Set<() => void>();

export function currentAccent(): AccentId {
  const saved = localStorage.getItem(KEY);
  return ACCENTS.some((a) => a.id === saved) ? (saved as AccentId) : "sky";
}

/** Subscribe to accent changes (for useSyncExternalStore). */
export function subscribeAccent(fn: () => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

export function setAccent(id: AccentId) {
  localStorage.setItem(KEY, id);
  applyAccent(id);
  for (const fn of listeners) fn();
}

/** Stamp the attribute; called once at startup and on every change. */
export function initAccent() {
  applyAccent(currentAccent());
}

function applyAccent(id: AccentId) {
  if (id === "sky") delete document.documentElement.dataset.accent;
  else document.documentElement.dataset.accent = id;
}
